config/routes.rb
ScoreProto::Application.routes.draw do
	match 'score_history' => 'raw_score_histories#index'
  resources :candidates do
    resources :raw_score_histories
    resources :energy
  end
  resources :recruiters
	resources :available_events
  resources :events
	resources :calculation_time_history

  namespace :admin do
    resources :available_events do as_routes end
    resources :pillars do as_routes end
		match "settings" => 'settings#index'
  end

  match 'login' => 'site#create'
  root to: "site#new"
end

app/models/available_event.rb
class AvailableEvent < ActiveRecord::Base
  has_many :events
  belongs_to :pillar 
end

app/models/calculation_time_history.rb
class CalculationTimeHistory < ActiveRecord::Base
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :events, as: :user
  has_many :raw_score_histories

  def self.active_in range
    Candidate.find(Event.by(Candidate).between(range).map(&:user_id).uniq)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user, :polymorphic => true
  belongs_to :available_event

	validates_presence_of :user_id
	validates_presence_of :user_type
	validates_presence_of :available_event_id
	


  scope :by, lambda { |who|
    if who.is_a? Class
      where(:user_type => who)
    else
      where(:user_type => who.class, :user_id => who.id)
    end
  }
  scope :in_pillar, lambda {|pillar| joins(:available_event).where("available_events.pillar_id = #{pillar.id}") }

  scope :between, lambda{|range| where(:created_at => (range.first..range.last))}

  def self.total_activity who, pillar, range
    self.by(who).in_pillar(pillar).between(range).select("sum(available_events.multiplier) as sum").map(&:attributes).first['sum'].to_i || 0
  end

  def self.energy(candidate_id)
		steps = 15
    (steps - self.where(:user_type => "Candidate", :user_id => candidate_id).where("created_at > ?", CalculationTimeHistory.last.time).count)*100/steps
  end

	def self.pillar_counts
		times = CalculationTimeHistory.last(2)
		events = self.where(:user_type => "Candidate").where("created_at > ?", times.first.time).where("created_at < ?", times.last.time)
		array = Pillar.all.collect{|p|
			count = events.where("available_event_id IN (?)", p.available_events.collect{|e| e.id}).count
			{p.name => count}
		}
		hash = {}
		array.each do |h|
			hash.merge! h
		end
		hash
	end
	
end

app/models/pillar.rb
class Pillar < ActiveRecord::Base
  has_many :available_events
end

app/models/raw_score_history.rb
class RawScoreHistory < ActiveRecord::Base
  belongs_to :candidate
  serialize :pillars, Hash

	def pillars(with_counts=true)
		if with_counts
			pillars = super()
			
		else
			super()
		end
	end
end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
  has_many :events, as: :user
end

app/controllers/admin/available_events_controller.rb
class Admin::AvailableEventsController < ApplicationController

  active_scaffold :available_event do |config|
    config.label = "available_event"
    config.columns = [:id, :event_name, :user_type, :pillar_id, :multiplier]
    config.create.columns = [:event_name, :user_type, :pillar_id, :multiplier]
    config.update.columns = [:event_name, :user_type, :pillar_id, :multiplier]
  end

end

app/controllers/admin/pillars_controller.rb
class Admin::PillarsController < ApplicationController

  active_scaffold :pillar do |config|
    config.label = "pillars"
    config.columns = [:id, :name, :weight]
    config.create.columns = [:name, :weight]
    config.update.columns = [:name, :weight]
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
	def index
		if params["show_counts"].present?
			if params[:show_counts] == "true"
				Rails.cache.write(:show_counts, true)
			elsif params[:show_counts] == "false"
				Rails.cache.write(:show_counts, false)
			end
			redirect_to admin_settings_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/available_events_controller.rb
class AvailableEventsController < ApplicationController
	def index
		respond_to do |format|
			format.json {
				if params['user_type']
					render :json => AvailableEvent.where(user_type: params["user_type"])
				else
					render :json => AvailableEvent.all
				end
			}
			format.csv	{ 
				@models = AvailableEvent.all
				render '/shared/index'
			}
		end
	end
end

app/controllers/calculation_time_history_controller.rb
class CalculationTimeHistoryController < ApplicationController
  respond_to :json
  
	def index
		last2 = CalculationTimeHistory.last(2)
		last_time = last2.last.updated_at
		interval  = last_time - last2.first.updated_at
		next_time = last_time + interval
		respond_with last_time: last_time, interval: interval.round, next_time: next_time
	end
  
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	def index
		respond_to do |format|
			format.json { render :json => Candidate.order('score DESC').all }
			format.csv	{ 
				@models = Candidate.all
				render '/shared/index'
			}
		end
	end
	
  def show
    @candidate = Candidate.find(params[:id])
    respond_to do |format|
			format.html
			format.json { render :json => @candidate }
		end  
	end
  
  def update
    respond_to do |format|
			format.json { render :json => @candidate }
		end
  end
  
end

app/controllers/energy_controller.rb
class EnergyController < ApplicationController
  respond_to :json

	def index

    render :json => {energy: Event.energy(params[:candidate_id])}.to_json
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
		respond_to do |format|
			format.json {render :json => @events}
			format.csv	{ 
				@models = @events
				render '/shared/index'
			}		
		end
	end
	
	def create		
    if Event.energy(params[:event][:user_id]) > 0
      e = Event.create(params[:event])
    end
		render :json => {energy: Event.energy(params[:event][:user_id])}.to_json
	end
end

app/controllers/raw_score_histories_controller.rb
class RawScoreHistoriesController < ApplicationController
	
	def index
		if params[:candidate_id]
			respond_to do |format|
				format.json {
					hists = Candidate.find(params[:candidate_id]).raw_score_histories.order('updated_at DESC').limit(20).collect{|h| h.attributes}
					hists[0][:pillar_counts] = Rails.cache.read(:show_counts) ? Event.pillar_counts : {}
						render :json => hists, :status => :ok
				}
			end
		else
			respond_to do |format|
				format.csv	{ 
					@models = RawScoreHistory.all
					render '/shared/index'
				}
			end	
		end
	end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
	def index
		respond_to do |format|
			format.csv	{ 
				@models = Recruiter.all
				render '/shared/index'
			}
		end
	end
	
  def show
    @recruiter = Recruiter.find(params[:id])
		@candidates = Candidate.order('score DESC')
    respond_to do |format|
			format.html
			format.json { render :json => @recruiter }
		end  
	end
  
  def update
    respond_to do |format|
			format.json { render :json => @recruiter }
		end
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def new
    
  end
  
  def create
    type = params[:user_type]
    user_name = params[:name]
    
    user = type.constantize.find_or_create_by_name(user_name)
    redirect_to user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/settings/index.html.erb
<% if Rails.cache.read(:show_counts)%>
  Showing counts<br>
  <%= button_to "Stop Showing", admin_settings_path(:show_counts => false) %>
<% else %>
  Not showing counts
  <%= button_to "Start Showing", admin_settings_path(:show_counts => true) %>
<% end %>

app/views/candidates/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'candidate' %>
<% end %>

<% content_for :header do %>
  <a class="btn" data-toggle="modal" href="#myModal" style="float:right;">How to play</a>

  <div class="modal" id="myModal" style="display: none; ">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>How to play</h3>
    </div>
    <div class="modal-body">
      The objective of the game is to Maximize your score at all times!</br>
      <ul id="fancy">
        <li>Your score goes from 0 to 100 and is subdivided into pillars.</li>
        <li>Each pillar has a different % of the total score, which is not revealed. These percentages could change at any moment.</li>
        <li>Each pillar's score is increased if you perform an action related to that pillar (for example, clicking A1 increases your A pillar score for that round).</li>
        <li>You have a limited number of actions to perform per round. At the end of every round (10 seconds long), your energy bar refills.</li>
        <li>The contributions window lets you know how much each pillar contributed to your score in the previous round.</li>
        <li>Use the information in the contributions window to decide where to spend your energy in the next round!</li>  </div>
      </ul>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
  </div>
<% end %>


<div class="row">
  <div id="candidate" class="span12" data-json="<%= @candidate.to_json %>">
    loading...
  </div>
</div>



<div class="row">
  <div class="span6">
    <h3>Events<span id="countdown"></span></h3>
    <div id="energy"></div>
    <ul id="available_events">
      loading...
    </ul>
  </div>
  
  <div class="span6">
    <h3>Contributions</h3>
    <div id="score-history">Waiting for computation</div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <h3>Score History</h3>
    <div id="avg-score-history" style="width:100%;height:300px; clear:both;">Waiting for computation</div>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScoreProto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header" class="container">  
  <%= yield :header %>
  <%= image_tag "identified-beta-logo.png" %>
</div>
<div id="container" class="container">
    <%= yield %>
</div>
</div>
</body>
</html>

app/views/recruiters/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'recruiter' %>
<% end %>

<div>
  <h1>Recruiter: <%= @recruiter.name %></h1>
</div>
<div class="row">
  <div id="actions" class="span4">
    <h3>Actions</h3>
    <ul id="available_events">
      loading...
    </ul>    
  </div>
  
  <div id="candidates" class="span8">
    <h3>Candidates</h3>
    <table id="candidates-table" class="table table-striped table-bordered">
    </table>
  </div>
</div>

app/views/shared/index.csv.erb
<%= @models.first.class.csv_header %>
<% @models.each do |m| %>
<%= m.to_csv %>
<% end %>

app/views/site/new.html.erb
<div style="height:25px">
  
</div>
<div class="row">
  <div class="span4 offset1">
    <b>Welcome to the Dynamic Score Prototype!</b>

    Unless otherwise directed, please select "Candidate" from the drop-down menu and type your name. Click "Submit" to play the game.
  </div>
  
  <div class="offset2 span4">
    <%= form_tag login_path, class: "well" do -%>
      
      <%= select_tag :user_type, options_for_select(["Candidate", "Recruiter"]), :include_blank => false, class: "fill-input"  %>
      <%= text_field_tag :name, "", class: "fill-input" %>
      <br><%= submit_tag "Login", class: "btn" %>
    <% end -%>
  </div>
</div>


<div class="row">
  <div class="offset4 span4 center-text">
    Brought to you by team Rolling Thunder.
  </div>
</div>